namespace Sim.Core.Scoring;

/// <summary>One entry of the in-game glossary: what the word means, and how this game uses it.</summary>
public sealed record GlossaryTerm(string Term, string Category, string Short, string Game, string? Page = null, string[]? See = null, string[]? Aka = null);

/// <summary>
/// The searchable glossary behind F2. Definitions are short and use the game's own numbers where they differ from a textbook; each entry can point to the
/// page where the thing is changed or shown. UI-free so that tests can check cross-references and page names.
/// </summary>
public static class Glossary
{
    public static readonly string[] Categories = { "Output and jobs", "Prices and money", "Public finances", "Tax and benefits", "Trade and the world", "Society and politics", "How the game works" };
    public static readonly string[] Pages = { "Dashboard", "Budget", "Monetary", "Policies", "Investment", "Sectors", "Trade", "Society", "Forecast", "World map", "Cabinet", "Rankings", "Journal", "Report" };

    static GlossaryTerm T(string term, string cat, string brief, string game, string? page = null, string[]? see = null, string[]? aka = null) => new(term, cat, brief, game, page, see, aka);

    public static readonly IReadOnlyList<GlossaryTerm> Terms = new[]
    {
        // ---- output and jobs ----
        T("Real GDP", "Output and jobs", "The value of everything produced in a year, adjusted for price changes.", "Growth is real GDP against a year ago. The Dashboard indexes it to 100 at the start of the game so you can see the path.", "Dashboard", new[] { "Nominal GDP", "Potential output" }),
        T("Nominal GDP", "Output and jobs", "GDP at today's prices, with no adjustment for inflation.", "Taxes, debt ratios and the interest bill are measured against nominal GDP, which is why inflation quietly shrinks debt ratios.", null, new[] { "Real GDP" }),
        T("Potential output", "Output and jobs", "What the economy can produce without pushing prices up: set by capital, labour, skills and technology.", "Six sectors build it from capital, labour, human capital, productivity and the quality of public assets. Investment lifts it slowly.", "Sectors", new[] { "Output gap", "TFP" }),
        T("Output gap", "Output and jobs", "How far actual output is above (positive) or below (negative) potential.", "A negative gap means slack: unemployment above its natural rate and pressure on prices to fall. A large positive gap overheats the economy and raises inflation.", "Dashboard", new[] { "Potential output", "Recession" }),
        T("Recession", "Output and jobs", "A period when output falls and sits below potential.", "The clock can stop for you when one starts (Settings, pause triggers). Approval, tax revenue and the deficit all react within a few months.", "Dashboard", new[] { "Output gap", "Automatic stabilisers" }),
        T("TFP", "Output and jobs", "Total factor productivity: output not explained by more capital or labour, such as better technology and organisation.", "It grows slowly, faster with research spending, infrastructure and skills, and slower under unrest. It is the main source of long-run growth.", "Sectors", new[] { "Potential output", "Human capital" }, new[] { "Productivity" }),
        T("Human capital", "Output and jobs", "The skills and health of the workforce.", "Built by education and health spending over many years; it raises productivity and lowers the natural rate of unemployment.", "Budget", new[] { "TFP" }),
        T("Unemployment rate", "Output and jobs", "The share of the labour force without a job that is looking for one.", "It follows the output gap (Okun's law) and drifts toward the natural rate. Its level feeds approval, the benefit bill and unrest.", "Dashboard", new[] { "NAIRU", "Okun's law" }),
        T("NAIRU", "Output and jobs", "The natural rate of unemployment: the level at which inflation neither speeds up nor slows.", "Starts at the country's calibrated rate and moves with your choices: a higher minimum wage relative to earnings, higher payroll tax and more generous or longer unemployment benefits raise it; better skills and labour-market reforms lower it. It also drifts slowly toward actual unemployment (hysteresis).", "Dashboard", new[] { "Unemployment rate", "Replacement rate" }, new[] { "Natural rate of unemployment", "Natural rate" }),
        T("Okun's law", "Output and jobs", "A rule of thumb linking the output gap to unemployment: when output runs below potential, unemployment rises above its natural rate.", "In the model unemployment is pulled toward the natural rate minus half the output gap, so a gap of minus 4% leaves it about two points above the natural rate.", null, new[] { "Output gap", "NAIRU" }),
        T("Hysteresis", "Output and jobs", "When a downturn leaves lasting damage: long-term unemployed lose skills and the natural rate rises.", "Unemployment more than a point above the natural rate builds a stock of long-term unemployed who drain away at about a fifth a year. The stock lifts the natural rate, by up to two points, and by more where unions protect insiders. The Society page shows both. Avoiding a slump is worth more than the output lost in it.", "Society", new[] { "NAIRU", "Collective bargaining" }),
        T("Labour share", "Output and jobs", "The share of national income paid as wages rather than profits.", "Follows bargaining power and falls in deep slumps and when real pay falls behind prices. A higher share lifts household spending a little and lowers measured inequality.", "Society", new[] { "Collective bargaining", "Gini" }),
        T("Participation rate", "Output and jobs", "The share of working-age people who are in work or looking for it.", "Marginal rates and benefit withdrawal move it: a high effective marginal rate on low earners keeps people out of work; raising the pension age keeps older people in.", "Budget", new[] { "Marginal tax rate", "Pension age" }),
        T("Fiscal multiplier", "Output and jobs", "How much output changes for each pound of extra government spending or tax cut.", "Not one number: it depends on who gets the money (poorer households spend more of it), on slack in the economy and on the interest-rate response. Unemployment and means-tested benefits lift demand most; pensions least; corporation-tax cuts barely at all in the first year.", "Budget", new[] { "Marginal propensity to consume", "Crowding out" }),
        T("Marginal propensity to consume", "Output and jobs", "The share of an extra pound of income that a household spends rather than saves.", "Poorer households spend more of each extra pound. The game scales a benefit's effect on demand by who receives it: unemployment ×1.30, means-tested ×1.25, housing ×1.20, disability ×1.12, child ×1.10, pensions ×0.85.", "Budget", new[] { "Fiscal multiplier" }, new[] { "MPC" }),
        T("Crowding out", "Output and jobs", "Government borrowing pushing up interest rates and squeezing private investment.", "Higher deficits and debt raise the sovereign spread and the yield, which lifts loan rates for firms.", null, new[] { "Yield", "Sovereign spread" }),
        T("Investment", "Output and jobs", "Spending on new capital: machines, buildings, roads, networks.", "Private investment follows loan rates, corporation tax and confidence; public projects are chosen on the Investment page and arrive years later, often over budget.", "Investment", new[] { "Capital spending" }),

        // ---- prices and money ----
        T("Inflation", "Prices and money", "The rate at which the general price level rises.", "It follows a Phillips curve: it rises when output is above potential, when expectations drift up and when import prices rise. Its distance from target drives approval and the central bank's rule.", "Dashboard", new[] { "Inflation target", "Inflation expectations" }),
        T("Inflation target", "Prices and money", "The inflation rate the central bank aims for.", "Usually 2%. The Taylor rule raises the policy rate when inflation is above it.", "Monetary", new[] { "Taylor rule" }),
        T("Inflation expectations", "Prices and money", "What households and firms expect inflation to be: they feed into wage and price setting.", "Anchored expectations make inflation easy to control; expectations drift when the central bank loses credibility, for example by monetising deficits.", "Monetary", new[] { "Credibility", "Inflation" }),
        T("Credibility", "Prices and money", "How far people believe the central bank will do what it takes to hit its target.", "A credible bank can calm inflation with small rate moves. Pinning the rate against the rule, or printing money for the deficit, wears it away; it rebuilds slowly.", "Monetary", new[] { "Inflation expectations", "Monetisation" }),
        T("Wage-price spiral", "Prices and money", "Prices rise, workers claim higher pay to catch up, firms pass the cost on, and prices rise again.", "Bargained pay answers the part of a price shock beyond a one-point band; about half the premium reaches prices. Bigger and longer where union coverage is high, smaller where the central bank is credible. The Society page shows the pp it adds to inflation.", "Society", new[] { "Collective bargaining", "Credibility", "Inflation expectations" }, new[] { "Wage spiral", "Second-round effects" }),
        T("Policy rate", "Prices and money", "The short-term interest rate set by the central bank.", "Under the default rule it follows the Taylor rule, limited to half a point a month. Pin it on the Monetary page and the slider shows the 3, 6 and 12-month effect before you commit.", "Monetary", new[] { "Taylor rule", "Real interest rate" }, new[] { "Interest rate", "Bank rate" }),
        T("Taylor rule", "Prices and money", "A rule of thumb that sets the policy rate from inflation and the output gap.", "The cabinet's default: rate = neutral rate + inflation + a weight on the inflation gap + a weight on the output gap.", "Monetary", new[] { "Policy rate", "Neutral rate" }),
        T("Neutral rate", "Prices and money", "The interest rate that neither speeds up nor slows the economy once inflation is at target.", "It is roughly the long-run real rate plus target inflation. Rates above it are tight; below it, loose.", "Monetary", new[] { "Real interest rate" }),
        T("Real interest rate", "Prices and money", "The interest rate after subtracting inflation: what borrowing actually costs.", "Saving, investment and the exchange rate respond to the real rate, not the headline one.", "Monetary", new[] { "Policy rate", "Inflation" }),
        T("Yield", "Prices and money", "The interest rate the government pays to borrow for ten years.", "The policy rate plus a sovereign spread. The interest bill follows it with a lag as old debt is refinanced.", "Dashboard", new[] { "Sovereign spread", "Interest bill" }, new[] { "10-year yield", "Gilt yield" }),
        T("Sovereign spread", "Prices and money", "The extra interest investors demand to lend to this government rather than a safe benchmark.", "It widens with debt above 60% of GDP, deficits above 4%, inflation above 5%, low stability, corruption, thin reserves and contagion from other countries. A wide spread feeds back into the interest bill.", "Dashboard", new[] { "Yield", "Debt-to-GDP" }),
        T("Zero lower bound", "Prices and money", "The point where the policy rate cannot usefully fall further.", "Rates can go slightly negative in the model, but further cuts add little, which is why deep recessions near zero need fiscal support.", "Monetary", new[] { "Policy rate" }, new[] { "ZLB" }),
        T("Monetisation", "Prices and money", "The central bank financing the government's deficit by creating money.", "It lowers borrowing costs for a while and wrecks credibility, so inflation expectations and the exchange rate pay for it later.", "Monetary", new[] { "Credibility" }),
        T("Exchange rate regime", "Prices and money", "Whether the currency floats, is managed, or is pegged to another.", "A peg holds until reserves or competitiveness run out, then breaks, usually with a sharp fall and a spike in inflation.", "Monetary", new[] { "Reserves", "Real exchange rate" }, new[] { "Peg", "Float" }),
        T("Real exchange rate", "Prices and money", "The exchange rate adjusted for relative prices: a measure of competitiveness.", "A strong real rate makes exports dearer and imports cheaper; a weak one the opposite. It drives the trade balance over a year or two.", "Monetary", new[] { "Exchange rate regime", "Current account" }),
        T("Reserves", "Prices and money", "Foreign currency held by the central bank, here measured in months of imports.", "Reserves defend a managed or pegged rate and reassure lenders. Running low invites a currency crisis and an IMF programme.", "Monetary", new[] { "Exchange rate regime", "IMF programme" }),

        // ---- public finances ----
        T("Budget deficit", "Public finances", "Spending (including interest) minus revenue, as a share of GDP.", "It rises in recessions because tax revenue falls and benefits rise, and with any structural gap between what you spend and what you raise.", "Budget", new[] { "Primary balance", "Automatic stabilisers" }),
        T("Primary balance", "Public finances", "The budget balance before interest payments.", "The part of the deficit you control today; the interest bill is the legacy of past borrowing.", "Budget", new[] { "Budget deficit", "Interest bill" }),
        T("Debt-to-GDP", "Public finances", "Public debt as a share of a year's national income.", "Debt rises with deficits and falls with growth and inflation. Above a country-specific comfort level the spread widens and the cabinet warns you.", "Dashboard", new[] { "Budget deficit", "Sovereign spread" }, new[] { "Public debt", "Debt ratio" }),
        T("Interest bill", "Public finances", "What the government pays each year to service its debt.", "Debt times the average rate on it. Moves slowly as maturing debt is refinanced at the current yield.", "Budget", new[] { "Yield", "Debt-to-GDP" }),
        T("Automatic stabilisers", "Public finances", "Tax revenue and benefit spending that cushion the economy without any decision: revenue falls and benefits rise in a downturn.", "They work with no use of political capital, which is why a recession widens the deficit even if you change nothing.", "Budget", new[] { "Recession", "Budget deficit" }),
        T("Fiscal drag", "Public finances", "Taxes rising as a share of income because thresholds are frozen while incomes grow.", "Set threshold indexation to frozen on the Income tax tab and more of each person's income falls into higher bands and loses the allowance, raising revenue without any rate change.", "Budget", new[] { "Indexation", "Personal allowance" }, new[] { "Bracket creep" }),
        T("Laffer curve", "Public finances", "Revenue rises with the tax rate up to a point, then falls as people work, invest or declare less.", "Revenue responses are concave: cuts rarely pay for themselves unless rates are already very high.", "Budget", new[] { "Marginal tax rate" }),
        T("Capital spending", "Public finances", "Government spending on lasting assets: roads, schools, networks.", "Builds public assets slowly and lifts potential output later; current spending (pay, benefits) does neither but supports demand and services now.", "Budget", new[] { "Investment" }, new[] { "Current spending" }),
        T("Austerity", "Public finances", "Cutting spending or raising taxes to reduce the deficit.", "Pays down debt over years but costs growth and approval first. Cuts to benefits and the allowance cost extra political capital.", "Budget", new[] { "Fiscal multiplier", "Political capital" }),
        T("Political capital", "Public finances", "Your standing to make unpopular choices: it is spent on policies, tax changes and overriding the central bank.", "Regenerates every month, faster when approval is high (roughly 1.2 to 3.4 a month), up to a cap of 100; capital left at the cap is wasted. What you stage this turn is charged when the turn is played.", "Policies", new[] { "Turn plan" }, new[] { "PC" }),

        // ---- tax and benefits ----
        T("Personal allowance", "Tax and benefits", "The amount of income you can earn before paying income tax.", "Set as a multiple of mean earnings on the Income tax tab. In several countries it is withdrawn at higher incomes (the taper).", "Budget", new[] { "Allowance taper", "Tax band" }, new[] { "Tax-free allowance", "Standard deduction" }),
        T("Allowance taper", "Tax and benefits", "The personal allowance shrinking as income passes a threshold.", "Taper start and rate are editable. Inside the taper the marginal rate is the band rate plus the allowance lost times it: in the UK, 60% between £100,000 and £125,140.", "Budget", new[] { "Personal allowance", "Marginal tax rate" }),
        T("Tax band", "Tax and benefits", "A slice of income taxed at one rate.", "You can have up to eight, each with its own threshold and rate. Only income above a threshold is taxed at that band's rate.", "Budget", new[] { "Marginal tax rate", "Average tax rate" }, new[] { "Tax bracket" }),
        T("Marginal tax rate", "Tax and benefits", "The share of the next pound earned that is lost to tax.", "The charts show it across the income range. It is what shapes decisions to work more, and it spikes where tapers and benefit withdrawal overlap.", "Budget", new[] { "Average tax rate", "METR" }),
        T("Average tax rate", "Tax and benefits", "Total tax divided by total income.", "Lower than the marginal rate while allowances and low bands apply; the take-home table shows it by income.", "Budget", new[] { "Marginal tax rate" }),
        T("METR", "Tax and benefits", "Effective marginal tax rate: tax, contributions and lost benefits on the next pound earned.", "The marginal-rate chart on the Income tax tab is a METR: it includes the allowance taper, employee contributions and the withdrawal of means-tested benefits.", "Budget", new[] { "Marginal tax rate", "Benefit withdrawal" }, new[] { "Effective marginal rate" }),
        T("Indexation", "Tax and benefits", "Raising thresholds or benefit rates each year with earnings or prices.", "Choose earnings, prices (CPI) or frozen. Frozen thresholds produce fiscal drag; frozen benefits fall behind living standards.", "Budget", new[] { "Fiscal drag" }),
        T("Payroll tax", "Tax and benefits", "Contributions paid on wages, by the employee and the employer, often funding pensions and health.", "The employer share raises the cost of hiring and so the natural rate of unemployment; the employee share lowers take-home pay.", "Budget", new[] { "NAIRU" }, new[] { "Social contributions", "National insurance", "NICs" }),
        T("Corporation tax", "Tax and benefits", "Tax on company profits.", "A higher rate deters investment and foreign direct investment but raises revenue now; a small-profits rate shelters small firms. In the first year it barely moves demand; its effect builds through capital.", "Budget", new[] { "Expensing", "FDI" }, new[] { "Corporate tax" }),
        T("Expensing", "Tax and benefits", "Letting firms deduct the full cost of an investment against profits immediately instead of over many years.", "Lowers the effective tax on new investment even if the headline rate is unchanged, so it boosts investment at a smaller revenue cost than a rate cut.", "Budget", new[] { "Corporation tax" }, new[] { "Capital allowances", "Full expensing" }),
        T("VAT", "Tax and benefits", "A tax on spending, charged at each stage of production and passed on to the final buyer.", "Standard and reduced rates plus seven category treatments (zero, reduced, standard, exempt). A rise lifts prices once and falls hardest on poorer households, who spend more of their income.", "Budget", new[] { "Regressive" }, new[] { "Sales tax", "Consumption tax", "GST" }),
        T("Shadow economy", "Tax and benefits", "Activity that goes unreported and so escapes tax: informal work, cash trade, hidden profits.", "Starts at a country-specific share. Heavier taxes and more corruption push it up; administration spending and compliance policies pull it down; it moves about a third of the way to its target each year. It shrinks or widens the tax base in proportion, so a tax rise raises less than the rates imply.", "Society", new[] { "Laffer curve", "Marginal tax rate" }, new[] { "Informal economy", "Tax evasion", "Black economy" }),
        T("Regressive", "Tax and benefits", "A tax or charge that takes a bigger share of income from poorer people.", "Consumption taxes are regressive; progressive income-tax bands are the opposite. The decile charts show who gains and loses from each change.", "Budget", new[] { "VAT" }),
        T("Tariff", "Tax and benefits", "A tax on imports.", "Raises revenue and protects domestic firms, but raises prices, invites retaliation and cuts trade. Set on the Trade page per partner.", "Trade", new[] { "Retaliation" }),
        T("Means test", "Tax and benefits", "Paying a benefit only to people with low income or assets.", "Cheaper per head and well targeted, but withdrawn as income rises, which adds to the marginal rate (the poverty trap).", "Budget", new[] { "Benefit withdrawal", "Poverty trap" }, new[] { "Means-tested" }),
        T("Benefit withdrawal", "Tax and benefits", "Reducing a means-tested benefit as income rises.", "Each pound earned loses a share of the benefit: it stacks on top of income tax and contributions in the METR.", "Budget", new[] { "METR", "Poverty trap" }, new[] { "Taper rate" }),
        T("Poverty trap", "Tax and benefits", "A situation where earning more leaves you little or no better off because benefits are withdrawn as quickly as pay rises.", "The welfare tab flags it when a household keeps less than 35p of each extra pound earned.", "Budget", new[] { "Benefit withdrawal" }),
        T("Replacement rate", "Tax and benefits", "A benefit as a share of the earnings it replaces.", "A high unemployment replacement rate supports demand in a recession but raises the natural rate of unemployment.", "Budget", new[] { "NAIRU" }),
        T("Pension age", "Tax and benefits", "The age at which the state pension starts.", "Raising it cuts the pension bill (about 13% for two years in the UK) and keeps older people working, but is unpopular with older voters and costs political capital.", "Budget", new[] { "Participation rate", "Dependency ratio" }, new[] { "Retirement age" }),
        T("Universal basic income", "Tax and benefits", "A payment to everyone regardless of income or work.", "Available as a policy on the Policies page. It overlaps the benefit levers on the Budget tab; the two are costed separately, so use one or the other.", "Policies", null, new[] { "UBI" }),

        // ---- trade and the world ----
        T("Current account", "Trade and the world", "The balance of trade in goods and services plus income from abroad.", "A deficit has to be financed by borrowing from or selling assets to the rest of the world; a large one raises the risk of a currency crisis.", "Trade", new[] { "Real exchange rate" }),
        T("FDI", "Trade and the world", "Foreign direct investment: foreign firms building or buying businesses at home.", "Attracted by low corporation tax and political stability, among other things; it adds to domestic investment.", "Trade", new[] { "Corporation tax" }),
        T("Gravity model", "Trade and the world", "Trade between two countries rises with their size and falls with distance and barriers.", "The trade layer uses it for partner flows, so a slump in a big neighbour hits your exports hard.", "Trade"),
        T("Contagion", "Trade and the world", "Trouble in one country spreading to neighbours and trade partners.", "Crisis scores spread along trade links and regions; the USD rate and world inflation come from the simulated US and advanced economies.", "World map"),
        T("Terms of trade", "Trade and the world", "The price of what you export relative to what you import.", "Resource exporters swing with commodity prices: an oil price fall cuts government revenue and export income together.", "Trade"),
        T("Sanctions", "Trade and the world", "Trade and financial restrictions imposed on a country.", "Imposed or lifted through the Trade page; they cut trade with the target and raise prices.", "Trade"),
        T("Retaliation", "Trade and the world", "A trading partner answering your tariffs with its own.", "AI governments retaliate when you raise tariffs on them, so a tariff war costs both sides.", "Trade", new[] { "Tariff" }),
        T("IMF programme", "Trade and the world", "A rescue loan from the IMF with conditions attached.", "Triggered by a debt or currency crisis. While it runs your freedom to loosen policy is limited.", null, new[] { "Reserves" }),

        // ---- society and politics ----
        T("Approval", "Society and politics", "The share of voters who support the government.", "Growth, jobs, prices, inequality, taxes, services and corruption all feed it. In democracies, the chance of winning an election is a logistic function of approval; autocracies face coup risk instead.", "Society", new[] { "Stability" }),
        T("Gini", "Society and politics", "A measure of income inequality from 0 (everyone equal) to 1 (one person has everything).", "Moves with taxes, benefits, unemployment and policy. The Budget estimates its change before you commit.", "Society", new[] { "Poverty rate" }, new[] { "Inequality" }),
        T("Poverty rate", "Society and politics", "The share of people with income below a poverty line (a fraction of the median).", "Benefits, the allowance and employment move it; the Budget estimate shows the effect of a change before you commit.", "Society", new[] { "Gini" }),
        T("Stability", "Society and politics", "A slow-moving measure of how steady the political and social order is.", "Drifts toward a level set by approval, corruption, democracy and unrest (itself driven by inequality, unemployment, inflation and low approval). Low stability deters foreign investment and raises the risk of a coup.", "Society", new[] { "Approval" }),
        T("Dependency ratio", "Society and politics", "Children and pensioners as a share of the working-age population.", "A rising ratio pushes up pension and health spending and slows growth; the Society page shows the three age cohorts.", "Society", new[] { "Pension age" }),
        T("Collective bargaining", "Society and politics", "Pay and conditions negotiated between unions and employers for a whole workforce, not person by person.", "Coverage and union strength set bargaining power. High power passes price shocks into pay faster, feeds the wage-price spiral, and raises strike risk and the scarring from long unemployment; it also keeps the labour share up. Union-rights and flexibility policies move coverage.", "Society", new[] { "Wage-price spiral", "Labour share", "Strike risk" }, new[] { "Unions", "Union coverage", "Bargaining power" }),
        T("Strike risk", "Society and politics", "The chance that workers walk out over pay.", "Rises when real pay has fallen more than a point behind prices, faster where bargaining power is high. It multiplies the chance of the strike-wave event, where conceding makes good most of the shortfall at a price in the budget and in inflation.", "Society", new[] { "Collective bargaining", "Wage-price spiral" }),
        T("Coalition", "Society and politics", "The strength of the legislative majority behind you.", "Policies need a vote. The chance of passing rises with coalition strength and approval and falls with how costly the policy is in political capital.", "Policies", new[] { "Political capital" }),

        // ---- how the game works ----
        T("Turn", "How the game works", "One month of simulated time.", "End turn (Enter) plays one month. The clock (Space, 1 to 4) plays turns for you; Run to stops at a date.", "Dashboard", new[] { "Turn plan" }),
        T("Turn plan", "How the game works", "The actions you have staged for this turn.", "Nothing changes in the world until the turn is played: political capital, news and adviser notes stay put so you can change your mind. The Plan tray lists cost and whether each action will succeed.", "Budget", new[] { "Political capital", "Preview" }, new[] { "Plan", "Staging" }),
        T("Preview", "How the game works", "A what-if run of the model on a copy of the game.", "Compares your plan and draft against carrying on, with noise and random events switched off, so the difference is caused by your choices only. It is an expected path, not a prediction.", "Budget", new[] { "Baseline" }),
        T("Baseline", "How the game works", "What happens if you change nothing.", "Previews and fan charts compare against it; the cabinet autopilot does not count as nothing.", "Forecast", new[] { "Preview" }, new[] { "Carry on" }),
        T("Fan chart", "How the game works", "A forecast drawn as a central path with bands showing how uncertain it is.", "Built by re-running the simulation many times with shocks; wider bands mean more risk.", "Forecast", new[] { "Baseline" }),
        T("Autopilot", "How the game works", "The cabinet running your tax, spending and interest-rate dials by simple rules.", "Competent, not clever: it never enacts policies, starts projects or does trade deals. Switch it on or off on the Cabinet page.", "Cabinet"),
        T("Auto-pause", "How the game works", "The running clock stopping itself when something needs your attention.", "Choose the triggers in Settings. A manual End turn never stops anywhere.", "Cabinet", new[] { "Turn" }),
        T("Scorecard", "How the game works", "Your grade: prosperity, living standards, stability, sustainability and resilience.", "Scenarios add goals to it. Difficulty changes how forgiving the game is.", "Report", null, new[] { "Grade", "Score" }),
    };

    static readonly Dictionary<string, GlossaryTerm> ByName = Terms.SelectMany(t => new[] { t.Term }.Concat(t.Aka ?? Array.Empty<string>()).Select(n => (n, t))).GroupBy(p => p.n, StringComparer.OrdinalIgnoreCase).ToDictionary(g => g.Key, g => g.First().t, StringComparer.OrdinalIgnoreCase);

    public static GlossaryTerm? Find(string name) => ByName.TryGetValue(name, out var t) ? t : null;

    /// <summary>Terms matching <paramref name="query"/>, best first: exact name, name prefix, other name or alias hit, then the wording of the explanation. Empty query lists everything alphabetically.</summary>
    public static List<GlossaryTerm> Search(string query, string? category = null)
    {
        var pool = Terms.Where(t => category == null || t.Category == category);
        string q = (query ?? "").Trim();
        if (q.Length == 0) return pool.OrderBy(t => t.Term, StringComparer.OrdinalIgnoreCase).ToList();
        var words = q.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        int Score(GlossaryTerm t)
        {
            string name = t.Term;
            if (name.Equals(q, StringComparison.OrdinalIgnoreCase)) return 100;
            if (t.Aka?.Any(a => a.Equals(q, StringComparison.OrdinalIgnoreCase)) == true) return 95;
            if (name.StartsWith(q, StringComparison.OrdinalIgnoreCase)) return 80;
            if (t.Aka?.Any(a => a.StartsWith(q, StringComparison.OrdinalIgnoreCase)) == true) return 75;
            if (name.Contains(q, StringComparison.OrdinalIgnoreCase)) return 60;
            if (t.Aka?.Any(a => a.Contains(q, StringComparison.OrdinalIgnoreCase)) == true) return 55;
            string body = t.Short + " " + t.Game;
            if (words.All(w => body.Contains(w, StringComparison.OrdinalIgnoreCase))) return 20;
            return 0;
        }
        return pool.Select(t => (t, s: Score(t))).Where(p => p.s > 0).OrderByDescending(p => p.s).ThenBy(p => p.t.Term, StringComparer.OrdinalIgnoreCase).Select(p => p.t).ToList();
    }
}
